### ISSUE TITLE
Can you add a restore option? 

### ISSUE THREAD

**Issue by seanbperiod** [blawar/incognito#2]
I wasn't prepared for this automatically changing the serial on load. Can you please add an option to restore from backup? 

Also, please add the option to confirm the change before doing so automatically.

**Comment by seanbperiod** [comment]
Thanks for adding the restore option! 

I just tried to restore, but I get:

 error: could not open prodinfo.bin
error: failed to import prodinfo.bin

I have not rebooted since running 1.0 and prodinfo.bin is in root. 
Running from SX homebrew menu.

**Comment by Zer0t3ch** [comment]
Haven't used it yet, but is the "backup" in any way encrypted or otherwise protected? Worried that if there's an accessible backup, it may not protect from malicious Homebrew.

**Comment by blawar** [comment]
@seanbperiod move your prodinfo.bin from your root SD directory, to the same directory as incognito.nro, i changed the location as people were confused by root.

**Comment by blawar** [comment]
@Zer0t3ch it is unencrypted, the readme states that  you should not keep the backup on your SD card so malicious homebrew cannot read it, please take it off of y our sd card.

**Comment by seanbperiod** [comment]
Thanks for your quick response on this @blawar !

**Comment by bakayaro77** [comment]
I successful to install the incognito mode in Atmosphere, but when I try to restore the original proinfo.bin, the error message come:
error: could not open prodinfo.bin
error: failed to import prodinfo.bin

I have tried to place the prodinfo.bin at incofnito.nro directory and root...also the same error.
Is it the file name is "prodinfo.bin" or "(myserialnumber)-prodinfo.bin"?

**Comment by bakayaro77** [comment]
Problem solved, i have typo the wrong file name that missing letter d.
