### ISSUE TITLE
Failed to read calibration data

### ISSUE THREAD

**Issue by PMcca** [blawar/incognito#22]
Currently using Atmosphere 0.92 and the incognito application doesn't work. Upon opening two errors are presented: 
error: failed to open cal0 partition
error: failed reading calibration data

**Comment by Rickardo987** [comment]
Atmosphere 0.92 auto blocks all read/write access to prodinfo for security concerns. This is a good thing but must be bypassed to use incognito. You can use SXOS or ReiNX (which dont have such safe measures in place) or (my solution) use the sysmodule found [here](https://gbatemp.net/threads/a-custom-sysmodule-for-atmosphere-that-allows-writing-to-prodinfo.541609/) in atmosphere to allow read/write access to prodinfo _temporary_. This module should be removed immediately after using incognito and, please, **BACK UP PRODINFO.BIN TO MULTIPLE LOCATIONS SO YOU DONT SCREW UP THE ONLINE ACCESS YOU ARE CLEARLY TRYING TO PROTECT!1!**

**Comment by blawar** [comment]
use the atmosphere fork in tinfoil to install incognito.
