### ISSUE TITLE
Incognito not working on SX OS 2.9.x

### ISSUE THREAD

**Issue by snoofly** [blawar/incognito#25]
Not sure if this is an incognito or SX problem but prior to SX 2.9 incognito could be installed fine.
As per https://team-xecuter.com/community/threads/sx-2-9-cant-to-used-incognito.132341/
there are issues writing to cal0 and wiping serial info with SX 2.9

**Comment by blawar** [comment]
use the atmosphere fork in tinfoil to install incognito.
